### 登录并获取token
GET http://127.0.0.1:8080/zc-login-provider/user/login?userName=admin&password=1
Accept: application/json

> {% client.global.set("Authorization", response.body.data); %}

### 获取用户信息
GET http://127.0.0.1:8080/zc-login-provider/user?userName=admin
Authorization: {{Authorization}}