spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_demo?useSSL=FALSE&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis扫描路径
mybatis:
  type-aliases-package: com.zc.common.model
  mapper-locations: classpath:mapper/*.xml

# 通用mapper
mapper:
  mappers:
    - com.zc.core.base.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true

# 分页mapper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    io:
      seata: debug