server:
  servlet:
    session:
      # 配置cookie相关信息
      cookie:
        # 将JSESSIONID修改为Authorization
        name: Authorization

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${config.ip}:3306/spring_cloud_demo?useSSL=FALSE&serverTimezone=Asia/Shanghai
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: ${config.ip}
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 10000

# mybatis扫描路径
mybatis:
  type-aliases-package: com.zc.common.model
  mapper-locations: classpath:mapper/*.xml

# 通用mapper
mapper:
  mappers:
    - com.zc.login.base.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true

# 分页mapper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

secret_key: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: debug